apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  annotations:
    serving.kserve.io/deploymentMode: RawDeployment
  labels:
    networking.kserve.io/visibility: exposed
  name: fraud
spec:
  predictor:
    model:
      modelFormat:
        name: onnx
      name: ""
      resources:
        limits:
          cpu: "2"
          memory: 2Gi
        requests:
          cpu: "2"
          memory: 2Gi
      runtime: fraud
      storage:
        key: odh-bucket
        path: models/mkumatag
