apiVersion: template.openshift.io/v1
kind: Template
metadata:
  annotations:
    opendatahub.io/apiProtocol: REST
    opendatahub.io/modelServingSupport: '["single"]'
  labels:
    opendatahub.io/dashboard: "true"
  name: triton-ppc64le-runtime
  namespace: redhat-ods-applications
objects:
- apiVersion: serving.kserve.io/v1alpha1
  kind: ServingRuntime
  metadata:
    annotations:
      opendatahub.io/apiProtocol: REST
      openshift.io/display-name: Triton Server ServingRuntime for KServe(ppc64le)
    labels:
      name: triton-ppc64le-runtime
    name: triton-ppc64le-runtime
  spec:
    containers:
    - command:
      - tritonserver
      - --model-repository=/mnt/models
      image: quay.io/powercloud/tritonserver:latest
      name: kserve-container
      ports:
      - containerPort: 8000
      resources:
        limits:
          cpu: 2
          memory: 8Gi
        requests:
          cpu: 2
          memory: 8Gi
    httpDataEndpoint: port:8000
    supportedModelFormats:
    - name: python
    - autoSelect: true
      name: onnx
